In [42]:
import pandas as pd
import numpy as np

##### 创建一个名为students的DataFrame，包含数据如下：
{"001":{"姓名":"小陈","考试1":85,"考试2":92,"考试3":92}，"002":{"姓名":"小李","考试1":91,"考试2":92,"考试3":94}，"003":{"姓名":"小王","考试1":86,"考试2":81,"考试3":89}，"004":{"姓名":"小张","考试1":79,"考试2":89,"考试3":95}，"005":{"姓名":"小赵","考试1":96,"考试2":91,"考试3":91}，"006":{"姓名":"小周","考试1":81,"考试2":89,"考试3":92}}
要求索引为学号（001,、002等），列名为姓名、考试1、考试2、考试3，并输出创建好的DataFrame。

In [4]:
student_data={"001":{"姓名":"小陈","考试1":85,"考试2":92,"考试3":92},"002":{"姓名":"小李","考试1":91,"考试2":92,"考试3":94},"003":{"姓名":"小王","考试1":86,"考试2":81,"考试3":89},"004":{"姓名":"小张","考试1":79,"考试2":89,"考试3":95},"005":{"姓名":"小赵","考试1":96,"考试2":91,"考试3":91},"006":{"姓名":"小周","考试1":81,"考试2":89,"考试3":92}}
students=pd.DataFrame(student_data).T
students

     姓名 考试1 考试2 考试3
001  小陈  85  92  92
002  小李  91  92  94
003  小王  86  81  89
004  小张  79  89  95
005  小赵  96  91  91
006  小周  81  89  92

##### 创建一个叫student_average的DataFrame.索引为学号，包含姓名列，以及计算出三次考试平均值后的结果列(列名为"平均分")。

In [35]:
average=students.loc[:,"考试1":"考试3"].mean(axis=1)
name=students["姓名"]
student_average=pd.DataFrame({"姓名":name,"平均分":average})
student_average

     姓名        平均分
001  小陈  89.666667
002  小李  92.333333
003  小王  85.333333
004  小张  87.666667
005  小赵  92.666667
006  小周  87.333333

##### 输出每次考试第二高的分数组成的Series，可以尝试结合匿名函数lambda。

In [46]:
grade=students.loc[:,"考试1":"考试3"].apply(lambda score: np.sort(score)[-2])
grade

考试1    91
考试2    92
考试3    94
dtype: int64

##### 根据以下规则，输出每个学号对应的四次考试的等级：  
A+:平均分>=95  
A:90<=平均分<95  
B+:85<=平均分<90  
B:80<=平均分<85  
C+:75<=平均分<80  
C:平均分<75

In [52]:
def level(grade):
    if grade>=95:
        return "A+"
    elif 90<=grade<95:
        return "A"
    elif 85<=grade<90:
        return "B+"
    elif 80<=grade<85:
        return "B"
    elif 75<=grade<80:
        return "C+"
    else:
        return"C"
students.loc[:,"考试1":"考试3"].map(level)

    考试1 考试2 考试3
001  B+   A   A
002   A   A   A
003  B+   B  B+
004  C+  B+  A+
005  A+   A   A
006   B  B+   A

##### 展示考试分数数列的统计信息。

In [62]:
students["考试1"]=students["考试1"].astype("int")
students["考试2"]=students["考试2"].astype("int")
students["考试3"]=students["考试3"].astype("int")
students.describe()

             考试1        考试2        考试3
count   6.000000   6.000000   6.000000
mean   86.333333  89.000000  92.166667
std     6.314006   4.147288   2.136976
min    79.000000  81.000000  89.000000
25%    82.000000  89.000000  91.250000
50%    85.500000  90.000000  92.000000
75%    89.750000  91.750000  93.500000
max    96.000000  92.000000  95.000000